services:
  # Frontend service
  - type: web
    name: spendsmart-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://spendsmart-backend.onrender.com

  # Backend service
  - type: web
    name: spendsmart-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        sync: false