services:
  - type: web
    name: spendsmart-backend
    env: node
    buildCommand: npm install --omit=dev && npm install --prefix backend
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production

  - type: static
    name: spendsmart-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://spendsmart-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html